base_url = "https://snorochevskiy.github.io"
compile_sass = true
build_search_index = true
taxonomies = [
    { name = "tags", feed = true},
]

[markdown]

[markdown.highlighting]
light_theme = "github-light"
dark_theme = "github-dark"

[extra]

